---
- name: "Set fqdn '{{ ansible_hostname }}' as hostname for physical nodes"
  become: yes
  hostname:
    name: "{{ ansible_hostname }}"
  tags:
    - cherubits
    - common
    - fqdn
    -
- name: "Add IP address of all hosts to all hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"