---

- hosts: ansible-role-common
  become: false
  gather_facts: true
  pre_tasks:
    - set_fact: fact_role_name="{{ lookup('env','ANSIBLE_ROLE_NAME') }}"
    - debug: var=fact_role_name
    - set_fact: fact_role_path="{{ lookup('pipe','pwd') }}/ansible-role-ansible-role-common"
    - debug: var=fact_role_path
  roles:
    - ansible-role-common
